-- Create product and product_category tables first
-- SELECT table_name FROM user_tables WHERE table_name IN ('PRODUCT_CATEGORY', 'PRODUCT', 'PRODUCT_ITEM', 'PROMOTION', 'VARIATION', 'VARIATION_OPTION', 'PRODUCT_CONFIGURATION');
--SELECT table_name FROM user_tables;
--select * from product_item;
BEGIN
  FOR t IN (SELECT table_name FROM user_tables) 
  LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
          RAISE;
        END IF;
    END;
  END LOOP;
END;
/
--DROP TABLE PRODUCT;
-- Create table product_category
select * from product_category;
CREATE TABLE product_category (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    parent_category_id NUMBER,
    category_name VARCHAR2(100),
    PRIMARY KEY(id)
);

-- Create table product
CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_id NUMBER,
    name VARCHAR2(100),
    description VARCHAR2(255),
    product_image VARCHAR2(255),
    PRIMARY KEY(id)
);

-- Create other tables
CREATE TABLE product_item (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id NUMBER,
    SKU VARCHAR2(50),
    quantity_in_stock NUMBER,
    product_image VARCHAR2(255),
    price NUMBER,
    PRIMARY KEY(id)
);

CREATE TABLE promotion (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    description VARCHAR2(255),
    discount_rate NUMBER,
    start_date DATE,
    end_date DATE,
    PRIMARY KEY(id)
);

CREATE TABLE promotion_category (
    category_id NUMBER,
    promotion_id NUMBER
);

CREATE TABLE variation (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_id NUMBER,
    name VARCHAR2(100),
    PRIMARY KEY(id)
);

CREATE TABLE variation_option (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    variation_id NUMBER,
    value VARCHAR2(100),
    PRIMARY KEY(id)
);

CREATE TABLE product_configuration (
    product_item_id NUMBER,
    variation_option_id NUMBER,
    PRIMARY KEY(product_item_id, variation_option_id)
);

INSERT INTO product ( category_id, name, description, product_image)
VALUES (1, 'Laptop', 'High-performance laptop', 'laptop.jpg');

INSERT INTO product_category (id, parent_category_id, category_name)
VALUES (1, NULL, 'Electronics');

INSERT INTO product_category (id, parent_category_id, category_name)
VALUES (2, NULL, 'Clothing');

INSERT INTO product_item ( product_id, SKU, quantity_in_stock, product_image, price)
VALUES (1, 'SKU123', 10, 'laptop1.jpg', 1500.00);

INSERT INTO product ( category_id, name, description, product_image)
VALUES (1, 'Smartphone', 'Latest smartphone model', 'smartphone.jpg');

INSERT INTO product_item ( product_id, SKU, quantity_in_stock, product_image, price)
VALUES (2, 'SKU456', 5, 'smartphone1.jpg', 1000.00);

INSERT INTO product ( category_id, name, description, product_image)
VALUES (2, 'T-Shirt', 'Comfortable cotton T-shirt', 'tshirt.jpg');

INSERT INTO product_item ( product_id, SKU, quantity_in_stock, product_image, price)
VALUES (3, 'SKU789', 20, 'tshirt1.jpg', 20.00);

-- Insert sample data into promotion table
INSERT INTO promotion ( name, description, discount_rate, start_date, end_date)
VALUES ('Summer Sale', 'Up to 50% off on selected items', 0.5, TO_DATE('2024-06-01', 'YYYY-MM-DD'), TO_DATE('2024-07-01', 'YYYY-MM-DD'));

INSERT INTO promotion ( name, description, discount_rate, start_date, end_date)
VALUES ('Clearance Sale', 'Last chance to buy at discounted prices', 0.3, TO_DATE('2024-04-01', 'YYYY-MM-DD'), TO_DATE('2024-04-30', 'YYYY-MM-DD'));

-- Insert sample data into variation and variation_option tables
INSERT INTO variation ( category_id, name)
VALUES (1, 'Color');

INSERT INTO variation_option ( variation_id, value)
VALUES (1, 'Red');

INSERT INTO variation_option ( variation_id, value)
VALUES (1, 'Blue');

-- Insert sample data into promotion_category table
INSERT INTO promotion_category (category_id, promotion_id)
VALUES (1, 1);

INSERT INTO promotion_category (category_id, promotion_id)
VALUES (1, 2);

select * from product_item;
select * from variation_option;
-- Insert sample data into product_configuration table
INSERT INTO product_configuration (product_item_id, variation_option_id)
VALUES (1, 1);

INSERT INTO product_configuration (product_item_id, variation_option_id)
VALUES (1, 2);

INSERT INTO product_configuration (product_item_id, variation_option_id)
VALUES (3, 2);

-- Add foreign key constraints after inserting data into tables
ALTER TABLE product
ADD CONSTRAINT fk_product_category_id FOREIGN KEY (category_id) REFERENCES product_category(id) ON DELETE SET NULL;

ALTER TABLE product_item
ADD CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE;

ALTER TABLE promotion_category
ADD CONSTRAINT fk_promotion_category_id FOREIGN KEY (category_id) REFERENCES product_category(id) ON DELETE SET NULL;

ALTER TABLE promotion_category
ADD CONSTRAINT fk_promotion_id FOREIGN KEY (promotion_id) REFERENCES promotion(id) ON DELETE SET NULL;

ALTER TABLE variation
ADD CONSTRAINT fk_variation_category FOREIGN KEY (category_id) REFERENCES product_category(id) ON DELETE SET NULL;

ALTER TABLE variation_option
ADD CONSTRAINT fk_variation_id FOREIGN KEY (variation_id) REFERENCES variation(id) ON DELETE CASCADE;

ALTER TABLE product_configuration
ADD CONSTRAINT fk_pc_product_item_id FOREIGN KEY (product_item_id) REFERENCES product_item(id) ON DELETE CASCADE;

ALTER TABLE product_configuration
ADD CONSTRAINT fk_pc_variation_option_id FOREIGN KEY (variation_option_id) REFERENCES variation_option(id) ON DELETE SET NULL;


